---
title: "SLO Animated"
output: html_document
---

```{r, include=FALSE, echo=FALSE, results=FALSE, warning=FALSE, comment=FALSE}

  knitr::opts_chunk$set(echo=FALSE, warning=FALSE, comment=FALSE)

# Install packages
  rm(list=ls())
  
  packages <- c("devtools", "Rcpp", "ggplot2", "gganimate", "gapminder", "dplyr", 
                  "installr", "animation", "tweenr", "ggforce", "plotly", "tidyr", 
                "MASS", "bindata", "gifski", "png", "transformr", "grid", "magick")
  lapply(packages, require, character.only = TRUE)

# Set the path for Image Magick
  # magickPath <- shortPathName("C:/Users/Christina Kim/Documents/R/library/ImageMagick-7.0.8-Q16/magick.exe")
  # magickPath <- shortPathName("C:/Program Files/ImageMagick-7.0.8-Q16/magick.exe")
  # animation::ani.options(convert = magickPath)
  
# Link for all gganimate documentation:
  "https://gganimate.com/reference/index.html"
  "https://github.com/thomasp85/gganimate/wiki"
  
# Next steps: Create style sheet
  "https://stackoverflow.com/questions/30446905/rmarkdown-font-size-and-header/30447045"

```

```{r, theme, include = FALSE}

# Assign colors for graphing subgroups 
  Both <- "#ff7373"
  ELL <- "#ffad5a" 
  SPED <- "#4f9da6"
  None <- "#280c64" 
    
  mycolors <- c( "None" = None, "ELL" = ELL, "SPED" = SPED, "Both" = Both)

# Create default theme    
  mytheme <-
    theme(
      panel.background = element_rect(fill = "white"), 
      axis.line = element_line(),
      legend.key=element_blank()
    )
    
# Guide to theme references:
 "https://ggplot2.tidyverse.org/reference/theme.html"
```

```{r, dataframe, include = FALSE, results = FALSE}

  n <- 1000
  rho.1 <- 0.75
  rho.2 <- .5
    
  train <- mvrnorm(n = n, mu = c(0, 0), Sigma = matrix(c(1, rho.1, rho.1, 1), nrow = 2), empirical = TRUE) %>% data.frame() %>%
    bind_cols(rmvbin(n = n, margprob = c(0.5, 0.5), bincorr = matrix(c(1, rho.2,rho.2, 1), ncol = 2)) %>% data.frame()) %>%
    mutate(id=row_number(),
           subgroup = factor(ifelse(X11 == 1 & X21 == 1, "Both", 
                             ifelse(X11 == 1, "ELL", 
                                    ifelse(X21 == 1, "SPED", "None"))),
                             levels = c("None", "ELL", "SPED", "Both"))) %>%
    rename(pretest = X1, posttest= X2, ELL = X11, SPED = X21) 
  
  train$posttest <- ifelse(train$subgroup=="Both", train$posttest - 1.15, 
                       ifelse(train$subgroup=="ELL", train$posttest - .65,
                              ifelse(train$subgroup=="SPED", train$posttest - .85, train$posttest)))

  cor(train[, sapply(train, is.numeric)],
      use = "complete.obs", method = "pearson")
```

```{r, model-train-test, include = FALSE, results = FALSE}
# Train model
  mod <- lm(posttest ~ pretest + ELL + SPED, train)
  
  yint.ell <- mod$coefficients[1] + mod$coefficients[3]
  yint.sped <- mod$coefficients[1] + mod$coefficients[4]
  yint.none <- mod$coefficients[1]
  yint.both <- mod$coefficients[1] + mod$coefficients[3] + mod$coefficients[4]
  
  beta = mod$coefficients[2]

# Test model
  pre = 0.5
  test <- data.frame(id = c(1001:1004), 
                            pretest = rep(pre, times = 4), 
                            subgroup = c("None", "ELL", "SPED", "Both"), 
                            ELL = c(0, 1, 0, 1), 
                            SPED = c(0, 0, 1, 1))
                     
  test$yhat <- round(predict(mod, newdata = test), digits = 2)
```

```{r, plot-train-model, fig.width = 6, fig.height = 5}
# Animate  
  reganim <- ggplot(train, aes(x = pretest, y = posttest, color = subgroup)) +
    
   # Layers 1 - 4
    geom_point(data = train[train$subgroup=="None", ], alpha = .75) +
    geom_point(data = train[train$subgroup=="ELL", ], alpha = .75) +
    geom_point(data = train[train$subgroup=="SPED", ], alpha = .75) +
    geom_point(data = train[train$subgroup=="Both", ], alpha = .75) + 

   # Layers 5 - 8
    geom_abline(intercept = yint.none, slope = beta, color = None, size = 1) +
    geom_abline(intercept = yint.ell, slope = beta, color = ELL, size = 1) +
    geom_abline(intercept = yint.sped, slope = beta, color = SPED, size = 1) +
    geom_abline(intercept = yint.both, slope = beta, color = Both, size = 1) +
    
    scale_colour_manual(breaks = c("None", "ELL", "SPED", "Both"), values = mycolors) + 

    labs(x = "Prior Achievement Score",
         y = "End of Year Score",
         color = "Student Profile") + 
    
    mytheme +

    transition_layers(layer_length = .5, transition_length = .25,
                    from_blank = TRUE, keep_layers = c(rep(Inf, 8))) +
    
   # Layers 1 - 4
    enter_appear() +
    enter_appear() +
    enter_appear() +
    enter_appear() +
    
   # Layers 4 - 8
    enter_appear() +
    enter_appear() +
    enter_appear() +
    enter_appear() 
  
  animate(reganim)
```

```{r, plot-test-model, fig.width = 6, fig.height = 5}
# Fitted values for None and Both
  yhat_none <- test$yhat[test$subgroup == "None"]
  yhat_both <- test$yhat[test$subgroup == "Both"]
  
# Grob for pretest annotation
  txt_pretest <- textGrob(paste("Pretest=", pre), gp = gpar(fontsize = 11, fontface = "bold"))
  
# Grobs for goal annotations  
  txt_yhat_none <- textGrob(paste("Goal=", yhat_none), gp = gpar(fontsize = 11, fontface = "bold"))
  txt_yhat_both <- textGrob(paste("Goal=", yhat_both), gp = gpar(fontsize = 11, fontface = "bold"))  
  
# Animate
 ggplot(train, aes(x = pretest, y = posttest, color = subgroup)) +
   
   geom_point(alpha = .75) + 
   
   # Best fit lines
    geom_abline(intercept = yint.none, slope = beta, color = None, size = 1) +
    geom_abline(intercept = yint.ell, slope = beta, color = ELL, size = 1) +
    geom_abline(intercept = yint.sped, slope = beta, color = SPED, size = 1) +
    geom_abline(intercept = yint.both, slope = beta, color = Both, size = 1) +
   
   # Pretest setup
     annotation_custom(txt_pretest, xmin = pre, xmax = pre, ymin = -Inf, ymax = -Inf) +
     geom_point(data = test[test$subgroup == "None", ], aes(x = pretest, y = -Inf), color="black") +
     geom_segment(aes(x = pre, xend = pre, y = -Inf, yend = yhat_none), color = "black", linetype = 2, size=.75) + 

   # Subgroup None
     geom_segment(aes(x = pre, xend = -Inf, y = yhat_none, yend = yhat_none), color = "black", linetype = 2, size = .75, arrow=arrow(length=unit(0.4,"cm"))) +
     geom_point(data = test[test$subgroup == "None", ], aes(x = -Inf, y = yhat_none), color="black") +
     annotation_custom(txt_yhat_none, xmin = -Inf, xmax = -Inf, ymin = yhat_none, ymax = yhat_none) + 

   # Subgroup Both
     geom_segment(aes(x = pre, xend = -Inf, y = yhat_both, yend = yhat_both), color = "black", linetype = 2, size = .75, arrow=arrow(length=unit(0.4,"cm"))) +
     geom_point(data = test[test$subgroup == "None", ], aes(x = -Inf, y = yhat_both), color="black") +
     annotation_custom(txt_yhat_both, xmin = -Inf, xmax = -Inf, ymin = yhat_both, ymax = yhat_both) +    
   
   # Transitions
     transition_layers(layer_length = .25, 
                      transition_length = .25,
                      from_blank = TRUE, 
                      keep_layers = c(4, rep(c(Inf, 15)))
                      ) +
   
   # Format
     coord_cartesian(clip = "off") +
       
     labs(x = "Prior Achievement Score",
     y = "End of Year Score",
     color = "Student Profile") + 
       
     mytheme
```

Simulate change in pretest & subgroup vs. goal:
```{r}
# https://github.com/thomasp85/gganimate/wiki/Animation-Composition
```

Try it yourself!:
```{r}
# Add shiny tool here
# https://bookdown.org/yihui/rmarkdown/shiny-embedded.html
```

